/**
 * Generated by anjay_codegen.py on 2021-01-31 20:47:40
 *
 * LwM2M Object: XCBR_Pos
 * ID: 34828, URN: urn:oma:lwm2m:ext:34828, Optional, Multiple
 *
 * This IPSO object is used to report the current time in seconds since
 * January 1, 1970 UTC. There is also a fractional time counter that has
 * a range of less than one second.
 */
#include <assert.h>
#include <stdbool.h>

#include <anjay/anjay.h>
#include <avsystem/commons/avs_defs.h>
#include <avsystem/commons/avs_list.h>
#include <avsystem/commons/avs_memory.h>

/**
 * Pos_stVal: R, Single, Mandatory
 * type: int, range: 0..3, unit: N/A
 * IEC 61850
 */
#define RID_POS_STVAL 29272

typedef struct xcbr_pos_instance_struct {
    anjay_iid_t iid;
    uint8_t pos_stval;
    uint8_t his_pos_stval;
    // TODO: instance state
} xcbr_pos_instance_t;

typedef struct xcbr_pos_object_struct {
    const anjay_dm_object_def_t *def;
    AVS_LIST(xcbr_pos_instance_t) instances;

    // TODO: object state
} xcbr_pos_object_t;

static inline xcbr_pos_object_t *
get_obj(const anjay_dm_object_def_t *const *obj_ptr) {
    assert(obj_ptr);
    return AVS_CONTAINER_OF(obj_ptr, xcbr_pos_object_t, def);
}

static xcbr_pos_instance_t *find_instance(const xcbr_pos_object_t *obj,
                                          anjay_iid_t iid) {
    AVS_LIST(xcbr_pos_instance_t) it;
    AVS_LIST_FOREACH(it, obj->instances) {
        if (it->iid == iid) {
            return it;
        } else if (it->iid > iid) {
            break;
        }
    }

    return NULL;
}

static int list_instances(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_dm_list_ctx_t *ctx) {
    (void) anjay;

    AVS_LIST(xcbr_pos_instance_t) it;
    AVS_LIST_FOREACH(it, get_obj(obj_ptr)->instances) {
        anjay_dm_emit(ctx, it->iid);
    }

    return 0;
}

static int init_instance(xcbr_pos_instance_t *inst, anjay_iid_t iid) {
    assert(iid != ANJAY_ID_INVALID);

    inst->iid = iid;
    // TODO: instance init
    inst->pos_stval = 1;//默认设置
    inst->his_pos_stval = inst->pos_stval;
    // TODO: return 0 on success, negative value on failure
    return 0;
}

static void release_instance(xcbr_pos_instance_t *inst) {
    // TODO: instance cleanup
    (void) inst;
}

static xcbr_pos_instance_t *
add_instance(xcbr_pos_object_t *obj, anjay_iid_t iid) {
    assert(find_instance(obj, iid) == NULL);

    AVS_LIST(xcbr_pos_instance_t) created =
            AVS_LIST_NEW_ELEMENT(xcbr_pos_instance_t);
    if (!created) {
        return NULL;
    }

    int result = init_instance(created, iid);
    if (result) {
        AVS_LIST_CLEAR(&created);
        return NULL;
    }

    AVS_LIST(xcbr_pos_instance_t) *ptr;
    AVS_LIST_FOREACH_PTR(ptr, &obj->instances) {
        if ((*ptr)->iid > created->iid) {
            break;
        }
    }

    AVS_LIST_INSERT(ptr, created);
    return created;
}

static int instance_create(anjay_t *anjay,
                           const anjay_dm_object_def_t *const *obj_ptr,
                           anjay_iid_t iid) {
    (void) anjay;
    xcbr_pos_object_t *obj = get_obj(obj_ptr);
    assert(obj);

    return add_instance(obj, iid) ? 0 : ANJAY_ERR_INTERNAL;
}

static int instance_remove(anjay_t *anjay,
                           const anjay_dm_object_def_t *const *obj_ptr,
                           anjay_iid_t iid) {
    (void) anjay;
    xcbr_pos_object_t *obj = get_obj(obj_ptr);
    assert(obj);

    AVS_LIST(xcbr_pos_instance_t) *it;
    AVS_LIST_FOREACH_PTR(it, &obj->instances) {
        if ((*it)->iid == iid) {
            release_instance(*it);
            AVS_LIST_DELETE(it);
            return 0;
        } else if ((*it)->iid > iid) {
            break;
        }
    }

    assert(0);
    return ANJAY_ERR_NOT_FOUND;
}

static int instance_reset(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid) {
    (void) anjay;

    xcbr_pos_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    xcbr_pos_instance_t *inst = find_instance(obj, iid);
    assert(inst);

    // TODO: instance reset
    inst->pos_stval = 1;
    inst->his_pos_stval = inst->pos_stval;
    return 0;
}

static int list_resources(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid,
                          anjay_dm_resource_list_ctx_t *ctx) {
    (void) anjay;
    (void) obj_ptr;
    (void) iid;

    anjay_dm_emit_res(ctx, RID_POS_STVAL,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    return 0;
}

static int resource_read(anjay_t *anjay,
                         const anjay_dm_object_def_t *const *obj_ptr,
                         anjay_iid_t iid,
                         anjay_rid_t rid,
                         anjay_riid_t riid,
                         anjay_output_ctx_t *ctx) {
    (void) anjay;

    xcbr_pos_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    xcbr_pos_instance_t *inst = find_instance(obj, iid);
    assert(inst);

    switch (rid) {
    case RID_POS_STVAL:
        assert(riid == ANJAY_ID_INVALID);
        if(inst->his_pos_stval != inst->pos_stval)
        {
            inst->pos_stval = inst->his_pos_stval;   
        }
        return anjay_ret_i32(ctx, inst->pos_stval); // TODO    


    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

int xcbr_pos_object_change_stval(int iid, anjay_dm_object_def_t **obj_ptr, int num)
{
    xcbr_pos_object_t *obj = get_obj(obj_ptr);
    xcbr_pos_instance_t *inst = find_instance(obj, iid);
    inst->his_pos_stval = num;
    return inst->his_pos_stval;
}


static const anjay_dm_object_def_t OBJ_DEF = {
    .oid = 34828,
    .handlers = {
        .list_instances = list_instances,
        .instance_create = instance_create,
        .instance_remove = instance_remove,
        .instance_reset = instance_reset,

        .list_resources = list_resources,
        .resource_read = resource_read,

        // TODO: implement these if transactional write/create is required
        .transaction_begin = anjay_dm_transaction_NOOP,
        .transaction_validate = anjay_dm_transaction_NOOP,
        .transaction_commit = anjay_dm_transaction_NOOP,
        .transaction_rollback = anjay_dm_transaction_NOOP
    }
};

const anjay_dm_object_def_t **xcbr_pos_object_create(void) {
    xcbr_pos_object_t *obj = (xcbr_pos_object_t *) avs_calloc(1, sizeof(xcbr_pos_object_t));
    if (!obj) {
        return NULL;
    }
    obj->def = &OBJ_DEF;

    // TODO: object init
    xcbr_pos_instance_t *inst = add_instance(obj, 0);
    if(inst)
    {
        inst->pos_stval = 1;
        inst->his_pos_stval = inst->pos_stval;
    }
    else
    {
        avs_free(obj);
        return NULL;
    }
    


    return &obj->def;
}

void xcbr_pos_object_release(const anjay_dm_object_def_t **def) {
    if (def) {
        xcbr_pos_object_t *obj = get_obj(def);
        AVS_LIST_CLEAR(&obj->instances) {
            release_instance(obj->instances);
        }

        // TODO: object cleanup

        avs_free(obj);
    }
}


void xcbr_pos_object_notify(anjay_t *anjay, const anjay_dm_object_def_t **def, uint8_t now_XCBR_Pos) {
    if (!anjay || !def) {
        return;
    }
    xcbr_pos_object_t *obj = get_obj(def);
    AVS_LIST(xcbr_pos_instance_t) it;
    AVS_LIST_FOREACH(it, obj->instances) {
        if (now_XCBR_Pos != it->pos_stval) {
            anjay_notify_changed(anjay, 34828, it->iid, RID_POS_STVAL);
        }
    }
}
